name: Build and deploy Python app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Prepare deployment package
        run: |
          # Créer un fichier requirements.txt si ce n'est pas déjà fait
          cp requirements_bert.txt requirements.txt
          
          # S'assurer que les scripts sont exécutables
          chmod +x startup.sh
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'air-paradis-sentiment-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
