name: Build and deploy Python app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Prepare deployment package
        run: |
          # Créer un fichier requirements.txt
          cp requirements_classical.txt requirements.txt
          
          # Créer un fichier wsgi.py simple
          echo "from api import app" > wsgi.py
          echo "" >> wsgi.py
          echo "if __name__ == \"__main__\":" >> wsgi.py
          echo "    app.run()" >> wsgi.py
          
          # S'assurer que le fichier startup.sh existe
          echo "#!/bin/bash" > startup.sh
          echo "cd /home/site/wwwroot" >> startup.sh
          echo "gunicorn --bind=0.0.0.0 --timeout 600 api:app" >> startup.sh
          chmod +x startup.sh
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'air-paradis-sentiment-api2'  # Utilisez le nouveau nom
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Vous devrez mettre à jour ce secret
          package: .