name: Build and deploy Python app to Azure - Reg Log

on:
  push:
    branches:
      - reg_log
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Prepare deployment package
        run: |
          # Créer un fichier requirements.txt depuis requirements_classical.txt
          cp requirements_classical.txt requirements.txt
          
          # S'assurer que les scripts sont exécutables
          chmod +x startup.sh
          
          # Renommer le fichier de configuration par défaut
          cp model_config_reglog.json model_config.json
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AE496B0C8B1C4FBF9467C2A9A69CAA40 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_307DB58F51644A8897077E2C525BFAE7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7517AB2BDD0A4ABBB44BE715714E19AD }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'air-paradis-sentiment-api-reglog'
          slot-name: 'Production'
          package: .